# Generated by Django 2.2.3 on 2019-07-23 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='motto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='motto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='pengalaman',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
